README.md
Closes #3 
Added a README to the repo...
=> Closes #3 Added README

server/db/models/category.js, tests/server/models/category-test.js
closes #10 
emerging from git hell
=> Closes #10

server/db/models/user.js, tests/server/models/user-test.js, tests/server/routes/members-only-test.js
Closes #5 
Completed user model & tests.
=> Closes #5 - Create user model

gulpfile.js, server/db/index.js, server/db/models/order.js, tests/server/models/order-test.js
=> Closes #7 - Create Order Model

server/db/models/review.js, tests/server/models/review-test.js
resolve conflict in gulp file (difference of one space) and index.js (include reviews model)
=> Resolve merge conflicts

gulpfile.js
=> removed head and master text

server/db/index.js
Added product, category, and review to index.js
=> Added models to the index.js file

server/db/models/review.js, tests/server/models/review-test.js
Closes #8 Add review model and tests
=> Closes #8 Add Review model

server/db/models/product.js, tests/server/models/product-test.js
removed extra comments from Product and product test
=> Removed silly comments

tests/server/models/category-test.js
removed extra comments from Product and product test
=> Removed category extra comments

server/db/index.js, server/db/models/category.js, server/db/models/order.js, tests/server/models/relations-test.js
=> Closes #11

browser/js/fsa/fsa-pre-built.js
Added a comment and isadmincheck
=> Added a comment

server/app/routes/utils.js
=> Closes #34

server/app/routes/index.js, tests/server/routes/review-routes-test.js
Closes #26 Tests for reviews route, and adds reviews and other files to api router
=> closes #26 Tests for reviews route

tests/server/routes/category-routes-tests.js
wrote specs for category routes
findall
admin only: create, edit, delete
=> F/category routes #54

server/app/routes/utils.js
=> Closes #51

server/app/configure/authentication/index.js
should fix session relations errors
=> Makes the authentication configuration return a promise

server/app/routes/utils.js
Checks if the user is logged in and is the resource's owner or is admin.
=> Helper func: check if user is resource's user/admin.

server/app/routes/orders.js, tests/server/routes/order-routes-test.js
=> Closes #13

browser/js/app.js, browser/js/products/products.html, browser/js/products/products.js, server/app/routes/products.js, server/db/models/product.js
Closes #93 Added defaultscope to product model, now only filtering by category on frontend, not backend.
=> Closes #93

server/app/routes/orders.js, server/db/index.js, server/db/models/order.js, tests/server/routes/order-routes-test.js
=> Closes #85

server/app/routes/reviews.js, tests/server/routes/review-routes-test.js
Create review routes for authenticated, unauth, and admin users, revise tests
=> Closes #16 create review routes

server/app/routes/orders.js
=> closes #98

browser/js/checkout/checkout.html, browser/js/checkout/checkout.js, browser/js/common/factories/orders-factory.js, server/app/routes/orders.js, tests/server/routes/order-routes-test.js
=> Closes #83

browser/js/checkout/checkout.js, browser/js/order-confirmation/order-confirmation.html, browser/js/order-confirmation/order-confirmation.js, tests/server/routes/order-routes-test.js
=> Closes #60

browser/js/checkout/checkout.html, browser/js/checkout/checkout.js, browser/js/common/factories/user-factory.js
=> Closes #108

browser/js/common/directives/order-history/order-history.html, browser/js/common/directives/order-history/order-history.js, browser/js/common/factories/orders-factory.js, browser/js/order-confirmation/order-confirmation.html, server/app/routes/orders.js, server/app/routes/users.js, server/db/models/order-products.js
Closes #117 , closes #122, closes #123
=> Closes #117, closes #122, closes #123

browser/js/common/directives/cart/cart.html
=> Closes #126

browser/js/checkout/checkout.html, browser/js/checkout/checkout.js, browser/js/common/directives/cart/cart.html, browser/js/common/directives/cart/cart.js, browser/js/order-confirmation/order-confirmation.html
closes #102, closes #121, closes #101
=> Closes #102, closes #121, closes #101

browser/js/common/factories/products-factory.js, browser/js/products/product.html, browser/js/products/products.js, browser/js/update-product/update-product.html, browser/js/update-product/update-product.js, server/app/routes/products.js
=> Closes #131

browser/js/products/product.html, browser/js/products/product.js, server/db/models/product.js
=> Closes #134

browser/js/account/account.html, browser/js/account/account.js, browser/js/common/directives/navbar/navbar.js, browser/js/order-confirmation/order-confirmation.html, server/db/models/product.js
closes #61 
Still need to write directive with name-change!
=> Closes #61

browser/js/common/directives/navbar/navbar.html, browser/js/common/directives/navbar/navbar.js, browser/js/common/directives/navbar/search-directive.js, browser/js/common/factories/products-factory.js, browser/js/products/products.html, browser/scss/directives/navbar.scss
=> Closes #97

browser/js/signup/signup.html, browser/js/signup/signup.js
Creates account if new, gives informative error if not. If successful, logs in and redirects to home.
=> Closes #71 New user signup state

browser/js/common/directives/navbar/navbar.html, browser/js/common/directives/navbar/navbar.js
=> Final edits to search bar

browser/js/products/products.html, browser/js/products/products.js
=> Closes #140

browser/js/admin-dashboard/admin-dashboard.html, browser/js/admin-dashboard/admin-dashboard.js, browser/js/common/factories/admin-factory.js, browser/js/common/factories/user-factory.js, server/app/routes/orders.js
Closes #104 Admin dashboard
Closes #73 Admin orders view
=> Closes #104 Create admin dashboard

browser/js/common/directives/navbar/navbar.html, browser/js/common/directives/navbar/navbar.js
=> closes #143
